package com.example.luyan.smartmenu_shop.GreenDao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.luyan.smartmenu_shop.Metadata.DESKITEM;

import com.example.luyan.smartmenu_shop.GreenDao.DESKITEMDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dESKITEMDaoConfig;

    private final DESKITEMDao dESKITEMDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dESKITEMDaoConfig = daoConfigMap.get(DESKITEMDao.class).clone();
        dESKITEMDaoConfig.initIdentityScope(type);

        dESKITEMDao = new DESKITEMDao(dESKITEMDaoConfig, this);

        registerDao(DESKITEM.class, dESKITEMDao);
    }
    
    public void clear() {
        dESKITEMDaoConfig.clearIdentityScope();
    }

    public DESKITEMDao getDESKITEMDao() {
        return dESKITEMDao;
    }

}
